/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlithongtin;

import java.awt.Window;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import libs.*;

/**
 *
 * @author Cường <duongcuong96 at gmail dot com>
 */
public class Quanlithongtin extends javax.swing.JPanel {

    private boolean isFileSelected = false;
    private String filepath = "";
    private DefaultTableModel model;
    private final DBManager dbmanager;

    private TableRowSorter<TableModel> rowSorter = null;
    private DateTimeManager datetimemanager = new DateTimeManager();
    private List<Field> data = new ArrayList<>();
    private long totalField = 0;
    private JLabel jlabel = new JLabel();

    /**
     * Creates new form main_view
     */
    public Quanlithongtin() throws SQLException {
        this.dbmanager = new DBManager("dbconfig");
        initComponents();
        model = (DefaultTableModel) mainTable.getModel();
        //enable table sorter
        rowSorter = new TableRowSorter(model);
        mainTable.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        mainTable.setRowSorter(rowSorter);

        //an nut edit
        btnEditField.hide();

        // khoi tao db
        MyConfig dbConfig = new MyConfig();
        dbConfig.loadConfig("dbconfig");
        String sql = "SELECT COUNT(id) FROM thong_tin";
        ResultSet records = dbmanager.query(sql);
        while (records.next()) {
            this.totalField = records.getInt(1);
        }
        System.out.println("Total Field : " + this.totalField);

        refresh();
    }

    public void refresh() throws SQLException {
        //lay danh sach field tu db ra :
        TableManager.removeAll(mainTable);
        ResultSet rs = dbmanager.query("SELECT * FROM thong_tin ");
        while (rs.next()) {
            Field f = new Field(
                    rs.getString(1), //id
                    rs.getString(2), //sdt user
                    rs.getString(3),//dau so
                    rs.getString(4), //noi dung
                    rs.getString(5)//thoi gian
            );
            TableManager.addRow(model, f);
            data.add(f);
        }
        System.out.println("total field : " + this.totalField);
    }

    public static void main(String[] args) throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        // select Look and Feel
        UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
        JFrame jf = new JFrame();
        jf.setResizable(false);
        jf.setSize(800, 700);
        jf.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        jf.setLocationRelativeTo(null);
        jf.add(new Quanlithongtin());
        jf.setVisible(true);
        System.out.println("ok run");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fieldContent1 = new javax.swing.JTable();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jTextField3 = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        fieldSendTo1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        fieldAdd1 = new javax.swing.JButton();
        btnSelectFile1 = new javax.swing.JButton();
        btnImportFile1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        fieldContent2 = new javax.swing.JTable();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        jTextField4 = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        fieldSendTo2 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        fieldAdd2 = new javax.swing.JButton();
        btnSelectFile2 = new javax.swing.JButton();
        btnImportFile2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        fieldContent3 = new javax.swing.JTable();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        jTextField5 = new javax.swing.JTextField();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        fieldSendTo3 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        fieldAdd3 = new javax.swing.JButton();
        btnSelectFile3 = new javax.swing.JButton();
        btnImportFile3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        btnSelectFile = new javax.swing.JButton();
        btnImportFile = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        fieldNumber = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        fieldAddBtn = new javax.swing.JButton();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        fieldSendTo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldContent = new javax.swing.JTextArea();
        fieldSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textInfo = new javax.swing.JLabel();
        btnEditField = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        fieldContent1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sdt", "Đầu số", "Thời gian", "Nội dung"
            }
        ));
        jScrollPane3.setViewportView(fieldContent1);

        label5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label5.setText("Thêm thông tin");

        label6.setText("số điện thoại");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        label7.setText("Nội dung");

        label8.setText("đầu số");

        fieldSendTo1.setToolTipText("Nhập đầu số");
        fieldSendTo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSendTo1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        fieldAdd1.setText("+");
        fieldAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAdd1ActionPerformed(evt);
            }
        });

        btnSelectFile1.setText("Chọn File");
        btnSelectFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFile1ActionPerformed(evt);
            }
        });

        btnImportFile1.setText("Nhập");
        btnImportFile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImportFile1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelectFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(fieldSendTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(703, 703, 703)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportFile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldSendTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)))
                .addGap(32, 32, 32))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        fieldContent2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sdt", "Đầu số", "Thời gian", "Nội dung"
            }
        ));
        jScrollPane5.setViewportView(fieldContent2);

        label9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label9.setText("Thêm thông tin");

        label10.setText("số điện thoại");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        label11.setText("Nội dung");

        label12.setText("đầu số");

        fieldSendTo2.setToolTipText("Nhập đầu số");
        fieldSendTo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSendTo2ActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane6.setViewportView(jTextArea3);

        fieldAdd2.setText("+");
        fieldAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAdd2ActionPerformed(evt);
            }
        });

        btnSelectFile2.setText("Chọn File");
        btnSelectFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFile2ActionPerformed(evt);
            }
        });

        btnImportFile2.setText("Nhập");
        btnImportFile2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImportFile2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelectFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(fieldSendTo2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(703, 703, 703)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportFile2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldSendTo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)))
                .addGap(32, 32, 32))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(800, 600));

        fieldContent3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sdt", "Đầu số", "Thời gian", "Nội dung"
            }
        ));
        jScrollPane7.setViewportView(fieldContent3);

        label13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label13.setText("Thêm thông tin");

        label14.setText("số điện thoại");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        label15.setText("Nội dung");

        label16.setText("đầu số");

        fieldSendTo3.setToolTipText("Nhập đầu số");
        fieldSendTo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSendTo3ActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane8.setViewportView(jTextArea4);

        fieldAdd3.setText("+");
        fieldAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAdd3ActionPerformed(evt);
            }
        });

        btnSelectFile3.setText("Chọn File");
        btnSelectFile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFile3ActionPerformed(evt);
            }
        });

        btnImportFile3.setText("Nhập");
        btnImportFile3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImportFile3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelectFile3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportFile3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(fieldSendTo3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(703, 703, 703)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectFile3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportFile3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldSendTo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(800, 650));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        mainTable.setBorder(null);
        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sdt", "Đầu số", "Thời gian", "Nội dung"
            }
        ));
        mainTable.setRowSorter(null);
        mainTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        mainTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                mainTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        mainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mainTable);
        if (mainTable.getColumnModel().getColumnCount() > 0) {
            mainTable.getColumnModel().getColumn(0).setHeaderValue("Sdt");
            mainTable.getColumnModel().getColumn(1).setHeaderValue("Đầu số");
            mainTable.getColumnModel().getColumn(2).setHeaderValue("Thời gian");
            mainTable.getColumnModel().getColumn(3).setHeaderValue("Nội dung");
        }

        btnSelectFile.setText("Chọn File");
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });

        btnImportFile.setText("Nhập");
        btnImportFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImportFileMouseClicked(evt);
            }
        });
        btnImportFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportFileActionPerformed(evt);
            }
        });

        btnRemove.setIcon(new javax.swing.ImageIcon("/home/cuong/NetBeansProjects/quanlithongtin/src/frontend/img/remove-symbol.resized.png")); // NOI18N
        btnRemove.setToolTipText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        label2.setText("số điện thoại");

        fieldNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumberActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("Thêm thông tin");

        fieldAddBtn.setIcon(new javax.swing.ImageIcon("/home/cuong/NetBeansProjects/quanlithongtin/src/frontend/img/plus-black-symbol.resized.png")); // NOI18N
        fieldAddBtn.setToolTipText("Thêm mới");
        fieldAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAddBtnActionPerformed(evt);
            }
        });

        label3.setText("Nội dung");

        label4.setText("đầu số");

        fieldSendTo.setToolTipText("Nhập đầu số");
        fieldSendTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSendToActionPerformed(evt);
            }
        });

        fieldContent.setColumns(20);
        fieldContent.setRows(5);
        jScrollPane2.setViewportView(fieldContent);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                            .addComponent(fieldNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldSendTo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNumber))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldSendTo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(fieldAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        label1.getAccessibleContext().setAccessibleName("d");
        label1.getAccessibleContext().setAccessibleDescription("");

        fieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchActionPerformed(evt);
            }
        });
        fieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldSearchKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlithongtin/magnifying-glass.resized.png"))); // NOI18N
        jLabel1.setToolTipText("Tìm kiếm");

        textInfo.setText("Tổng số : ");

        btnEditField.setFont(new java.awt.Font("Droid Sans", 0, 8)); // NOI18N
        btnEditField.setIcon(new javax.swing.ImageIcon("/home/cuong/NetBeansProjects/quanlithongtin/src/frontend/img/pencil.resized.png")); // NOI18N
        btnEditField.setToolTipText("Sửa");
        btnEditField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnImportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldSearch)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textInfo)
                .addGap(21, 21, 21)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldSendToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSendToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSendToActionPerformed
//nut them row cho db  , them vao table va them vao db ! 
    private void fieldAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAddBtnActionPerformed
        //tien hanh insert :
        List<String> errorsList = new ArrayList<String>();
        String contentField = "";
        String sendToField = "";
        String numberField = "";

        if (!fieldNumber.getText().isEmpty() && fieldNumber.getText().matches("^\\d+")) {
            numberField = fieldNumber.getText();
        } else {
            errorsList.add("NUMBER_FIELD_NULL");
        }

        if (!fieldContent.getText().isEmpty()) {
            contentField = fieldContent.getText();
        } else {
            errorsList.add("CONTENT_FIELD_NULL");
        }

        if (!fieldSendTo.getText().isEmpty() && fieldSendTo.getText().matches("^\\d+")) {
            sendToField = fieldSendTo.getText();
        } else {
            errorsList.add("SEND_TO_FIELD_NULL");
        }

        if (errorsList.contains("NUMBER_FIELD_NULL") || errorsList.contains("CONTENT_FIELD_NULL") || errorsList.contains("SEND_TO_FIELD_NULL")) {
            JOptionPane.showMessageDialog(null, "Hãy điền đầy đủ và chính xác  thông tin ! ");
        } else {
            String now = datetimemanager.now();
            //lay id tiep theo :
            ResultSet lastSqlId = dbmanager.query("SELECT id FROM thong_tin ORDER BY id DESC LIMIT 1");
            int currentSqlId = 0;
            try {
                while (lastSqlId.next()) {
                    currentSqlId = lastSqlId.getInt(1) + 1;
                }
            } catch (SQLException ex) {
                Logger.getLogger(Quanlithongtin.class.getName()).log(Level.SEVERE, null, ex);
            }

            Field currentField = new Field(Integer.toString(currentSqlId), numberField, sendToField, now, contentField);
            System.out.println("currentField " + currentField);
            TableManager.addRow(model, currentField);
            data.add(currentField);
            //add to db
            String sql = "INSERT INTO thong_tin(sdt,dau_so,thoi_gian,noi_dung) VALUES(?,?,?,?)";
            String[] args = {numberField, sendToField, now, contentField};
            dbmanager.insert(sql, args);
            //clear text
            fieldNumber.setText("");
            fieldSendTo.setText("");
            fieldContent.setText("");
        }

    }//GEN-LAST:event_fieldAddBtnActionPerformed

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
        JFileChooser filechooser = new JFileChooser();
        filechooser.setFileFilter(new FileNameExtensionFilter("import text log file ( .txt ) ", "txt"));
        filechooser.showDialog(label1, "open");
        if (filechooser != null) {
            filepath = filechooser.getSelectedFile().getAbsolutePath();
            isFileSelected = true;
            System.out.println("clicked,  importFileMouseClicked , file path : " + filepath);
        } else {
            System.out.println("selectect file was aborted ! ");
        }

    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void fieldNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumberActionPerformed

    private void btnImportFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportFileMouseClicked

    }//GEN-LAST:event_btnImportFileMouseClicked

    private void btnImportFile3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportFile3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportFile3MouseClicked

    private void btnSelectFile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFile3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectFile3ActionPerformed

    private void fieldAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAdd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAdd3ActionPerformed

    private void fieldSendTo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSendTo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSendTo3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void btnImportFile2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportFile2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportFile2MouseClicked

    private void btnSelectFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectFile2ActionPerformed

    private void fieldAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAdd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAdd2ActionPerformed

    private void fieldSendTo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSendTo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSendTo2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnImportFile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportFile1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportFile1MouseClicked

    private void btnSelectFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectFile1ActionPerformed

    private void fieldAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAdd1ActionPerformed

    private void fieldSendTo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSendTo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSendTo1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
//tien hanh nhap import file vao db + insert vao table  
    private void btnImportFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportFileActionPerformed
        if (isFileSelected == true) {
//            jlabel.setText("đang tải dữ liệu , vui lòng chờ ....");
//            JOptionPane.showMessageDialog(null, jlabel);

//              JOptionPane opt = new JOptionPane("đang tải dữ liệu , vui lòng chờ ....",JOptionPane.WARNING_MESSAGE);
//              final JDialog dlg = opt.createDialog("err");
//
//           Thread t2 = new Thread(){
//                public void run(){
//                 dlg.setVisible(true);
//                }
//            };
//           t2.start();
             
//            Thread t1 = new Thread() {
//                public void run() {
                    dbmanager.importText(filepath);
                    List<Field> allField = dbmanager.getData();
                    String sql = "INSERT INTO thong_tin(sdt,dau_so,thoi_gian,noi_dung) VALUES(?,?,?,?)";
                    for (int i = 0; i < dbmanager.getSize(); i++) {
                        Field currentField = allField.get(i);
                        String[] args = {currentField.menuId, currentField.phone, currentField.time, currentField.content};
                        dbmanager.insert(sql, args);
                        TableManager.addRow(model, currentField);
                    }
//                    dlg.setVisible(false);
//                }
//            };
//            t1.start();
            
        } else {
            System.out.println("File or database already imported or no file being selected ! ");
        }


    }//GEN-LAST:event_btnImportFileActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        //on remove rows
        if (mainTable.getSelectedRows().length > 1) {
//            int currentFieldId = mainTable.convertRowIndexToModel(mainTable.getSelectedRow());
//            Field currentField = data.get(currentFieldId);
//            int[] selectedRows = mainTable.getSelectedRows();
//            String[] sqlIdArr = {};
            List sqlIdArr = new ArrayList<String>();
            String table = "thong_tin";
            List selectedRowsList = new ArrayList<String>();
            System.out.println("SElected rows : ");
            for (int i = 0; i < mainTable.getSelectedRows().length; i++) {
//                int currentFieldId = mainTable.convertRowIndexToModel(selectedRows[i]);
//                Field currentField = data.get(currentFieldId);
//                String sqlId = currentField.sqlId;
//                sqlIdArr[i] =sqlId;
//                sqlIdArr.add(Integer.toString(i));
//                System.out.println("row id : " + selectedRows[i]);
//                System.out.println("sqlid : " + sqlId);
//                model.removeRow(0);
//                data.remove(currentFieldId);

//                 dbmanager.delete(sqlId, table);
//                System.out.println("Rows removed ");
                System.out.print(mainTable.getSelectedRows()[i] + " ");

            }

            int lengthx = mainTable.getSelectedRows().length;
            int[] rows = mainTable.getSelectedRows();
            for (int i = lengthx - 1; i >= 0; i--) {
                int currentFieldId = mainTable.convertRowIndexToModel(rows[i]);
                Field currentField = data.get(currentFieldId);
                String sqlId = currentField.sqlId;
                model.removeRow(rows[i]);
                data.remove(currentFieldId);
                dbmanager.delete(sqlId, table);

            }

//            dbmanager.batchDelete(sqlIdArr, table);
//            for (int i = 0; i < selectedRows.length; i++) {
//                int currentFieldId = mainTable.convertRowIndexToModel(selectedRows[i]);
//                Field currentField = data.get(currentFieldId);
//                String sqlId = currentField.sqlId;
//                dbmanager.delete(sqlId, table);
//                
//                model.removeRow(selectedRows[i]);
//                data.remove(curr`entFieldId);
//                System.out.println("Rows removed ");
//            }
        }
        if (mainTable.getSelectedRows().length == 1) {
            int currentFieldId = mainTable.convertRowIndexToModel(mainTable.getSelectedRow());
            Field currentField = data.get(currentFieldId);
            String sqlId = currentField.sqlId;
            String table = "thong_tin";

            model.removeRow(mainTable.getSelectedRow());
            data.remove(currentFieldId);

            dbmanager.delete(Integer.parseInt(sqlId), table);
            System.out.println("Row removed ! ");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void mainTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTableMouseClicked
        //khi bam vao row -> hien thi cac thong tin ra de edit 
        int currentFieldId = mainTable.convertRowIndexToModel(mainTable.getSelectedRow());
        Field currentField = data.get(currentFieldId);
        System.out.println("Current Field : " + currentField);
        fieldNumber.setText(model.getValueAt(mainTable.getSelectedRow(), 0).toString());
        fieldSendTo.setText(model.getValueAt(mainTable.getSelectedRow(), 1).toString());
        fieldContent.setText(model.getValueAt(mainTable.getSelectedRow(), 3).toString());

        //neu selected Row = 1 thi cho hien nut sua 
        if (mainTable.getSelectedRows().length == 1) {
            System.out.println("show");
            btnEditField.setVisible(true);
        } else {
            System.out.println("hide");
            btnEditField.setVisible(false);
        }

        //new selected rows > 1 cho hien thi nut xoa
        if (mainTable.getSelectedRows().length > 0) {
            btnRemove.setVisible(true);
        } else {
            btnRemove.setVisible(false);
        }
    }//GEN-LAST:event_mainTableMouseClicked

    private void fieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSearchActionPerformed

    private void fieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSearchKeyReleased
        //tim kiem :
        String searchString = fieldSearch.getText();
        if (searchString.trim().length() > 0) {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchString));
        } else {
            rowSorter.setRowFilter(null);
        }
    }//GEN-LAST:event_fieldSearchKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void btnEditFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFieldActionPerformed
        //edit field , khi user click vafo 1 field duy nhat thi cho phep chinh sua field do !
        int currentFieldId = mainTable.convertRowIndexToModel(mainTable.getSelectedRow());
        Field currentField = data.get(currentFieldId);
        List errorsList = new ArrayList();
        String contentField = "";
        String sendToField = "";
        String numberField = "";
        String now = datetimemanager.now();

        if (!fieldNumber.getText().isEmpty() && fieldNumber.getText().matches("^\\d+")) {
            numberField = fieldNumber.getText();
        } else {
            errorsList.add("NUMBER_FIELD_NULL");
        }

        if (!fieldContent.getText().isEmpty()) {
            contentField = fieldContent.getText();
        } else {
            errorsList.add("CONTENT_FIELD_NULL");
        }

        if (!fieldSendTo.getText().isEmpty() && fieldSendTo.getText().matches("^\\d+")) {
            sendToField = fieldSendTo.getText();
        } else {
            errorsList.add("SEND_TO_FIELD_NULL");
        }

        if (errorsList.contains("NUMBER_FIELD_NULL") || errorsList.contains("CONTENT_FIELD_NULL") || errorsList.contains("SEND_TO_FIELD_NULL")) {
            JOptionPane.showMessageDialog(null, "Hãy điền đầy đủ và chính xác  thông tin ! ");
        } else {
            String sql = "UPDATE thong_tin SET sdt = ? , dau_so = ? , thoi_gian = ? , noi_dung = ?  WHERE id = ?";
            String[] paras = {fieldNumber.getText(), fieldSendTo.getText(), now, fieldContent.getText(), currentField.sqlId};
            dbmanager.update(sql, paras);

            Field updateField = new Field(currentField.sqlId, numberField, sendToField, now, contentField);
            data.add(currentFieldId, updateField);
            TableManager.updateRow(mainTable, numberField, currentFieldId, 0); //phone number 
            TableManager.updateRow(mainTable, sendToField, currentFieldId, 1); //sendto number
            TableManager.updateRow(mainTable, now, currentFieldId, 2); //time 
            TableManager.updateRow(mainTable, contentField, currentFieldId, 3); //content
            //clear text
            fieldNumber.setText("");
            fieldSendTo.setText("");
            fieldContent.setText("");
        }
    }//GEN-LAST:event_btnEditFieldActionPerformed

    private void mainTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mainTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_mainTableAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditField;
    private javax.swing.JButton btnImportFile;
    private javax.swing.JButton btnImportFile1;
    private javax.swing.JButton btnImportFile2;
    private javax.swing.JButton btnImportFile3;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JButton btnSelectFile1;
    private javax.swing.JButton btnSelectFile2;
    private javax.swing.JButton btnSelectFile3;
    private javax.swing.JButton fieldAdd1;
    private javax.swing.JButton fieldAdd2;
    private javax.swing.JButton fieldAdd3;
    private javax.swing.JButton fieldAddBtn;
    private javax.swing.JTextArea fieldContent;
    private javax.swing.JTable fieldContent1;
    private javax.swing.JTable fieldContent2;
    private javax.swing.JTable fieldContent3;
    private javax.swing.JTextField fieldNumber;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JTextField fieldSendTo;
    private javax.swing.JTextField fieldSendTo1;
    private javax.swing.JTextField fieldSendTo2;
    private javax.swing.JTextField fieldSendTo3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTable mainTable;
    private javax.swing.JLabel textInfo;
    // End of variables declaration//GEN-END:variables

}
